name: CI

# Controls when the action will run.
# For GITHUB_TOKEN, read permissions are granted by default. 
# Write permissions must be explicitly enabled.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # build job
  build:  
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    # Steps may include the use of an action, a built-in Docker action, or a script.
    steps:
      # Checks-out your repository into the temporary GitHub Actions runner.
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint with Biome
        run: npx @biomejs/biome lint --apply

      - name: Format with Biome
        run: npx @biomejs/biome format --apply

      - name: Build Project
        run: npm run build

      - name: Run Vitest
        run: npm run test:unit

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-performance-monitor-extension
          path: dist/
